server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school?useSSL=false&serverTimezone=UTC
    username: school
    password: school123456
    driver-class-name: com.mysql.cj.jdbc.Driver
